server {
    listen 80;
    server_name localhost;

    # 1. Frontend Statik Web Dosyalarını Sunma
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Ters Yönlendirme (Reverse Proxy) - API Gateway Entegrasyonu
    # Kullanıcının /api/ ile başlayan HER isteği arka plandaki Gateway'e iletilir
    # proxy_pass sonundaki slash (/) yapısı "/api" kalıntısını silerek temiz port açar.
    location /api/ {
        proxy_pass http://api-gateway:8080/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
